<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0+
 * @link    http://my.studiopress.com/themes/genesis/
 */

//* Template Name: Category

//* Remove standard post content output
//remove_action( 'genesis_post_content', 'genesis_do_post_content' );

remove_action( 'genesis_loop', 'genesis_do_loop' );
add_action( 'genesis_loop', 'category_loop_helper' );

function category_loop_helper(){
    if( function_exists('genesis_grid_loop')){
        genesis_grid_loop( array(
			'features' => 1,
			'feature_image_size' => 'category',
			'feature_image_class' => 'align left post-image',
			'feature_content_limit' => 200,
			'grid_image_size' => 'category',
			'grid_image_class' => 'align left post-image',
			'grid_content_limit' => 0,
			'more' => __( 'Read more', 'genesis' ),
			'posts_per_page' => 5,
		) );
        
    }else{
        genesis_standard_loop();
    }
}



/**
 * This function outputs sitemap-esque columns displaying all pages,
 * categories, authors, monthly archives, and recent posts.
 *
 * @since 1.6
 * 
 * 
 */

genesis();
 ?>